### ISSUE TITLE
Installation of this theme fails due to lack of style.css file

### ISSUE THREAD

**Issue by oskosk** [Automattic/default-blogging-theme-dev#1]
When attempting to install this theme as instructed in the readme, WordPress complains because the zip files does not contain a `style.css` file.  The steps to reproduce are:

1. In admin panel, go to Appearance > Themes and click the Add New.
2. Click Upload and Choose File, then select [this theme's ZIP file](https://github.com/Automattic/default-blogging-theme-dev/archive.master.zip). Click Install Now.
3. Click Activate to use your new theme right away.

![image](https://user-images.githubusercontent.com/746152/46258162-32bd2900-c49c-11e8-9b74-51036e932375.png)

**Comment by oskosk** [comment]
@mendezcode clarified that stable releases of this theme, are available as releases,, and for development, running `make` after cloning is necessary.

**Comment by mendezcode** [comment]
Hey @oskosk – I have created a new release, which contains a new theme.

Also, added a [readme](https://github.com/Automattic/default-blogging-theme-dev/blob/master/readme.md) file, with infromation related to the build process.

**Comment by oskosk** [comment]
Excellent !!! gracias!
